version: '2'
services:
  nginx:
    image: nginx
    depends_on:
      - ghost
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - proxy

  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=password
    networks:
      - db

  ghost:
    build: ./ghost
    container_name: ghost
    depends_on:
      - mysql
    networks:
      - db
      - proxy

volumes:
  mysql:
networks:
  proxy:
  db:
